<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="User-PC" name="Teacher.ValidateCreateAssignment" tests="30" failures="5" timestamp="11 Jan 2017 12:23:22 GMT" time="3299.190" errors="0">
  <testcase name="Validate" time="242.250" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="2.369" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="243.716" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="49.251" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="61.945" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="61.210" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="47.464" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="224.638" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="137.972" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="242.139" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="141.785" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="2.247" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="28.716" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:156)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Validate -->
  <testcase name="Validate" time="137.081" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="43.744" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="166.291" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="28.900" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:156)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Validate -->
  <testcase name="Validate" time="137.776" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="195.396" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="152.732" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="43.442" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="242.824" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="154.182" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="2.035" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="28.429" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:156)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:44)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Validate -->
  <testcase name="Validate" time="194.988" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="2.566" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="226.101" classname="Teacher.ValidateCreateAssignment"/>
  <testcase name="Validate" time="28.363" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:156)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:44)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Validate -->
  <testcase name="Validate" time="28.638" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:156)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Validate -->
</testsuite> <!-- Teacher.ValidateCreateAssignment -->
