<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="Login" tests="3" failures="1" timestamp="11 May 2017 01:56:52 GMT" time="78.834" errors="0">
  <testcase name="LoginD" time="26.35" classname="Common.Login">
    <skipped/>
  </testcase> <!-- LoginD -->
  <testcase name="LoginD" time="26.307" classname="Common.Login">
    <skipped/>
  </testcase> <!-- LoginD -->
  <testcase name="LoginD" time="26.174" classname="Common.Login">
    <failure type="java.lang.AssertionError" message="Login Failed for:maym@inpods.com expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed for:maym@inpods.com expected [true] but found [false]
	at Common.Login.LoginD(Login.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginD -->
</testsuite> <!-- Login -->
