<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INPOD" name=" Validate_AssignmentCreation+Project+SQ+Group Assignment/project:yes;PodGroup_1" tests="2" failures="1" timestamp="4 Dec 2016 18:58:19 GMT" time="44.166" errors="0">
  <testcase name="selectSection" time="14.976" classname="Common.ChangeSection"/>
  <testcase name="Validate" time="29.123" classname="Teacher.ValidateCreateAssignment">
    <failure type="junit.framework.AssertionFailedError" message="new Assignment with name Get created- case failed">
      <![CDATA[junit.framework.AssertionFailedError: new Assignment with name Get created- case failed
	at junit.framework.Assert.fail(Assert.java:57)
	at Teacher.ValidateCreateAssignment.create(ValidateCreateAssignment.java:155)
	at Teacher.ValidateCreateAssignment.Validate(ValidateCreateAssignment.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Validate -->
</testsuite> <!--  Validate_AssignmentCreation+Project+SQ+Group Assignment/project:yes;PodGroup_1 -->
