<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="AttemptAll1" tests="1" failures="1" timestamp="2 Dec 2016 12:53:07 GMT" time="26.799" errors="0">
  <testcase name="AttemptTest" time="26.779" classname="assignment_Student.AttemptSurey">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at assignment_Student.AttemptSurey.AttemptSurvey(AttemptSurey.java:67)
	at assignment_Student.AttemptSurey.AttemptTest(AttemptSurey.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AttemptTest -->
</testsuite> <!-- AttemptAll1 -->
